# Generated by Django 3.0.6 on 2020-06-01 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=50)),
                ('created_date', models.DateField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=90, verbose_name='project title')),
                ('category', models.CharField(choices=[('Arts', 'Arts'), ('Charity', 'Charity'), ('Film', 'Film'), ('Food', 'Food'), ('Games', 'Games'), ('Music', 'Music'), ('Publishing', 'Publishing'), ('Technology', 'Technology')], max_length=10)),
                ('description', models.CharField(max_length=50000, verbose_name='project description')),
                ('backers_story', models.CharField(max_length=50000, verbose_name="what's in it for the backers?")),
                ('goal', models.IntegerField(default=0)),
                ('end_date', models.DateField(default=datetime.datetime(2020, 7, 1, 11, 59, 49, 58347))),
                ('num_raised', models.IntegerField(default=0)),
                ('num_views', models.IntegerField(default=0)),
                ('num_days', models.IntegerField(default=0)),
            ],
        ),
    ]
